Director.create!([
  {name: "COOK, TIM", jurisdiction_code: "us_al", position: "organizer", occupation: nil, company_name: "TASC Farm LLC", company_number: 334},
  {name: "COOK, TIM", jurisdiction_code: "us_al", position: "agent", occupation: nil, company_name: "TASC Farm LLC", company_number: 334},
  {name: "COOK, TIM D", jurisdiction_code: "us_al", position: "member", occupation: nil, company_name: "TASC Farm LLC", company_number: 334},
  {name: "Cook, Tim", jurisdiction_code: "us_ms", position: "agent", occupation: nil, company_name: "Cook's Sewing Machine Center, LLC", company_number: 988515},
  {name: "Cook, Tim", jurisdiction_code: "us_mo", position: "agent", occupation: nil, company_name: "Tim & Jan's Fireworks LLC", company_number: 0},
  {name: "Cook, Tim", jurisdiction_code: "us_dc", position: "governor", occupation: nil, company_name: "Commanders LLC", company_number: 0},
  {name: "Cook, Tim", jurisdiction_code: "us_ms", position: "agent", occupation: nil, company_name: "Tim Cook Development, LLC", company_number: 883562},
  {name: "Cook, Tim", jurisdiction_code: "us_nc", position: "agent", occupation: nil, company_name: "5.12 V-Grip, LLC", company_number: 1030488},
  {name: "MARION TIM COOK", jurisdiction_code: "us_ar", position: "agent", occupation: nil, company_name: "T. C. COOK, INC.", company_number: 100160699},
  {name: "TIM A COOK", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "COOK'S TREE SERVICE L.L.C.", company_number: 0},
  {name: "TIM A COOK", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "CIRCLE C SERVICES, \"LLC\"", company_number: 0},
  {name: "TIM A COOK", jurisdiction_code: "us_in", position: "secretary", occupation: nil, company_name: "COOK'S GLASS & MIRROR, INC.", company_number: 1991110190},
  {name: "TIM A COOK", jurisdiction_code: "us_in", position: "president", occupation: nil, company_name: "COOK'S GLASS & MIRROR, INC.", company_number: 1991110190},
  {name: "TIM A. COOK", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "COOK'S GLASS & MIRROR, INC.", company_number: 1991110190},
  {name: "TIM C COOK", jurisdiction_code: "us_ut", position: "agent", occupation: nil, company_name: "NATIONAL INSTALLATION SPECIALISTS LLC", company_number: 6372946},
  {name: "TIM COOK", jurisdiction_code: "gb", position: "director", occupation: "MANAGER", company_name: "THE OXFORD FINE CHEMICAL COMPANY LIMITED", company_number: 2664054},
  {name: "TIM COOK", jurisdiction_code: "us_ky", position: "incorporator", occupation: nil, company_name: "FIRST BAPTIST CHURCH OF MAYFIELD, KENTUCKY, INC.", company_number: 435955},
  {name: "TIM COOK", jurisdiction_code: "gb", position: "director", occupation: nil, company_name: "EVOTEC (UK) LIMITED", company_number: 2674265},
  {name: "TIM COOK", jurisdiction_code: "us_ak", position: "director", occupation: nil, company_name: "CENTER FOR PROFESSIONAL TEACHING AND LEARNING", company_number: 64911},
  {name: "TIM COOK", jurisdiction_code: "gb", position: "director", occupation: "PROVISION OF FIRST AID SERVICES", company_name: "CUSTOM FIRST AID LIMITED", company_number: 9577760},
  {name: "TIM COOK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "WALNUT GROVE FIREFIGHTERS ASSOCIATION", company_number: 0},
  {name: "TIM COOK", jurisdiction_code: "ca", position: "director", occupation: nil, company_name: "CANADA'S NATIONAL HISTORY SOCIETY", company_number: 2973774},
  {name: "TIM COOK", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "COOK QUALITY CONSTRUCTION INC.", company_number: 0},
  {name: "TIM COOK", jurisdiction_code: "us_tn", position: "agent", occupation: nil, company_name: "TAILWIND AVIATION, LLC", company_number: 421426},
  {name: "TIM COOK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "NEWMARKET INDUSTRIES, INC.", company_number: 0},
  {name: "TIM COOK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "TRIUMPH STUDIOS, INC.", company_number: 0},
  {name: "TIM COOK", jurisdiction_code: "us_ga", position: "cfo", occupation: nil, company_name: "CABCO USA, INC.", company_number: 11007096},
  {name: "TIM COOK", jurisdiction_code: "us_ga", position: "secretary", occupation: nil, company_name: "CHAMISA, INC.", company_number: 11061055},
  {name: "TIM COOK", jurisdiction_code: "gb", position: "secretary", occupation: nil, company_name: "LOCAL NETWORK TELEVISION LTD", company_number: 7550760},
  {name: "TIM COOK", jurisdiction_code: "us_ne", position: "president", occupation: nil, company_name: "SANDHILLS TILE & STONE, INC.", company_number: 10059245},
  {name: "MARK S ZUCKERBERG", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "AMERICAN CONSUMER BANKRUPTCY COLLEGE, INC.", company_number: 2004092400215},
  {name: "MARK S ZUCKERBERG", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "BANKRUPTCYCYA.COM, LLC", company_number: 2005080800155},
  {name: "MARK S ZUCKERBERG, PC", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "WALTON LEGAL SERVICES 2 LLC", company_number: 2014071000685},
  {name: "MARK S. ZUCKERBERG", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "BANKRUPTCY LAW OFFICE OF MARK S. ZUCKERBERG, P.C.", company_number: 1998021785},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "ceo", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "THEFACEBOOK LLC", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 3842367},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 1132412},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "Facebook, Inc.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_mn", position: "chief executive officer", occupation: nil, company_name: "Facebook, Inc.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "treasurer", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ct", position: "ceo/director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 883875},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "Mark Zuckerberg", jurisdiction_code: "us_in", position: "president", occupation: nil, company_name: "BANKRUPTCY LAW OFFICE OF MARK S. ZUCKERBERG, P.C.", company_number: 1998021785},
  {name: "Mark Zuckerberg", jurisdiction_code: "us_ga", position: "cfo", occupation: nil, company_name: "FWD.us, Inc", company_number: 17110153},
  {name: "Mark, Zuckerberg", jurisdiction_code: "us_nc", position: "president", occupation: nil, company_name: "Facebook, Inc.", company_number: 864380},
  {name: "mark zuckerberg", jurisdiction_code: "us_in", position: "president", occupation: nil, company_name: "AMERICAN CONSUMER BANKRUPTCY COLLEGE, INC.", company_number: 2004092400215},
  {name: "ELON MUSK", jurisdiction_code: "us_ct", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 1075301},
  {name: "ELON MUSK", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 1077847},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "NEW WORLD INDUSTRIES, LLC", company_number: 201315610070},
  {name: "ELON MUSK", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 603589622},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "president/ceo", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "chairman of the board", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 4832094},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "director", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 4238655},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ri", position: "director", occupation: nil, company_name: "SolarCity Corporation", company_number: 920073},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "member", occupation: nil, company_name: "SOLAR INTEGRATED FUND III, LLC", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "chr", occupation: nil, company_name: "Space Exploration Technologies Corp.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "coe", occupation: nil, company_name: "Space Exploration Technologies Corp.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "chief executive officer", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 4832094},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 602455888},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "Tesla Motors, Inc.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ma", position: "ceo", occupation: nil, company_name: "TESLA, INC.", company_number: 1077847},
  {name: "ELON MUSK", jurisdiction_code: "gb", position: "director", occupation: "CEO", company_name: "SURREY SATELLITE TECHNOLOGY LIMITED", company_number: 1916260},
  {name: "ELON MUSK", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "TESLA, INC. OF LOUISIANA", company_number: 41303273},
  {name: "ELON MUSK", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 801471675},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_tx", position: "officer", occupation: nil, company_name: "TESLA, INC.", company_number: 801471675},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "TESLA, INC.", company_number: 602932644},
  {name: "ELON MUSK", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "MUSK VENTURES, LLC", company_number: 200115210031},
  {name: "ELON MUSK", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "WORLD SPINE CARE", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "TESLA MOTORS", company_number: 3824277},
  {name: "ELON MUSK", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 602924061},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "BFR INTERNATIONAL CORP.", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_nv", position: "president", occupation: nil, company_name: "AMAZON.COM FINANCIAL SERVICES, INC.", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "AMAZON.COM INSURANCE SERVICES, INC.", company_number: 602030690},
  {name: "JEFF BEZOS", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "NET MANAGERS, LLC", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "AMAZON.COM.AS, INC.", company_number: 602032753},
  {name: "JEFF BEZOS", jurisdiction_code: "us_in", position: "president", occupation: nil, company_name: "LIVEBID.COM, INC.", company_number: 2000101700002},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "LIVEBID.COM, INC.", company_number: 601983997},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "TELEBOOK, INC.", company_number: 601872306},
  {name: "Jeff Bezos", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "NET MANAGERS, LLC", company_number: 0},
  {name: "EDWARD PETER VAN THIEL", jurisdiction_code: "gb", position: "director", occupation: "DIRECTOR", company_name: "COUNTRYWIDE DISTRIBUTION LIMITED", company_number: 4144228},
  {name: "EDWARD PETER VAN THIEL", jurisdiction_code: "gb", position: "director", occupation: "DIRECTOR", company_name: "EDWARD VAN THIEL LIMITED", company_number: 5825479},
  {name: "HANS PETER THIEL", jurisdiction_code: "pa", position: "director", occupation: nil, company_name: "COMERCIAL DA YU, S.A.", company_number: 10291},
  {name: "HANS PETER THIEL Y OTRO", jurisdiction_code: "pa", position: "secretario", occupation: nil, company_name: "COMERCIAL DA YU, S.A.", company_number: 10291},
  {name: "PETER A THIEL", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "PETER M THIEL", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "CAP FERRAT TROIS, L.L.C.", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "NTS SEARCH MARKETING LLC", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "MARCO PRIME TIME, L.L.C.", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "NTS SEARCH MARKETING LLC", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "in", position: nil, occupation: nil, company_name: "FRAUSCHER SENSOR TECHNOLOGY INDIA PRIVATE LIMITED", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "in", position: nil, occupation: nil, company_name: "FRAUSCHER RAIL SIGNALLING SYSTEMS INDIA PRIVATE LIMITED", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "gb", position: "director", occupation: "MANAGING DIRECTOR", company_name: "FRAUSCHER UK LIMITED", company_number: 7184154},
  {name: "PETER N THIEL", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "TRAIL RIDGE TRADING, INC.", company_number: 800230099},
  {name: "PETER N THIEL", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "TRAIL RIDGE TRADING, INC.", company_number: 800230099},
  {name: "PETER P THIEL", jurisdiction_code: "us_oh", position: "incorporator", occupation: nil, company_name: "MICROSYSTEM DESIGNS, INC.", company_number: 736806},
  {name: "PETER THIEL", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 41446269},
  {name: "PETER THIEL", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "PETER THIEL", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "PETER THIEL ENGINEERING INC.", company_number: 2014110500141},
  {name: "PETER THIEL", jurisdiction_code: "us_ct", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 883875},
  {name: "PETER THIEL", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "PETER THIEL", jurisdiction_code: "us_ri", position: "director", occupation: nil, company_name: "Palantir Technologies Inc.", company_number: 822270},
  {name: "PETER THIEL", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 603164223},
  {name: "PETER THIEL", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "PETER THIEL", jurisdiction_code: "us_va", position: "chairman", occupation: nil, company_name: "Palantir Technologies Inc.", company_number: 0},
  {name: "Peter Andreas THIEL", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "SECOND STAR LIMITED", company_number: 2378750},
  {name: "Peter Brooke Thiel", jurisdiction_code: "us_mn", position: "agent", occupation: nil, company_name: "Shiloh Studios LLC", company_number: 0},
  {name: "Peter Martin Thiel Søbjerg", jurisdiction_code: "dk", position: "interessenter", occupation: nil, company_name: "Thiel4", company_number: 39234408},
  {name: "Peter N Thiel", jurisdiction_code: "us_co", position: "agent", occupation: nil, company_name: "Trail Ridge Trading, Inc", company_number: 20051412887},
  {name: "Peter THIEL", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "SILVERARC ADVISORS LLC", company_number: 3061116},
  {name: "Peter Thiel", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 0},
  {name: "JEFF A WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "CW MERCHANDIZE LIQUIDATORS, LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "vice president", occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "JMW REALTY CORP.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "MDW Insurance Services, Inc.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "secr", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "trea", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "MDW SOUTH, LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "EMBRACE WELLNESS LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "VIP RISK ADVISORS LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "A.I.R. INSURANCE MARKETING, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "secretary", occupation: nil, company_name: "JMW REALTY CORP.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 1077535},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 14109071},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "A.I.R. INSURANCE MARKETING, INC.", company_number: 1172312},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 1079691},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 3348018},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 3348018},
  {name: "JEFF E WEINER", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "MARCO UNIVERSAL, INC.", company_number: 0},
  {name: "JEFF HOWARD WEINER", jurisdiction_code: "gb", position: "director", occupation: "NATIONAL ACCOUNTS MANAGER", company_name: "CD INVITES U LTD", company_number: 4779770},
  {name: "JEFF HOWARD WEINER", jurisdiction_code: "gb", position: "director", occupation: "SALES MANAGER", company_name: "JEA MUSIC MANAGEMENT LIMITED", company_number: 3754689},
  {name: "JEFF W WEINER", jurisdiction_code: "us_va", position: "treasurer", occupation: nil, company_name: "Automotive Reconditioning Services, Inc.", company_number: 7314727},
  {name: "JEFF WEINER", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "INTUIT INC.", company_number: 601422317},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "PREMFIN CORPORATION", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "A-1 TILE INC.", company_number: 2302292},
  {name: "JEFF WEINER", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 800988016},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "I & J HOLDINGS LLC", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: "vice president", occupation: nil, company_name: "PREMFIN CORPORATION", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "JDJ&S ENTERPRISES, LLC", company_number: 0},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "JAMCAT INVESTMENTS LLC", company_number: 0},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_ma", position: "real property", occupation: nil, company_name: "WW 51 MELCHER LLC", company_number: 1110668},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_ma", position: "real property", occupation: nil, company_name: "WW 745 ATLANTIC LLC", company_number: 1110665},
  {name: "Adam NEUMANN", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "NEUMANN CONTRACTORS LIMITED", company_number: 2083458},
  {name: "Adam NEUMANN", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "D A BUILDERS LIMITED", company_number: 3928982},
  {name: "Eric Adam Neumann", jurisdiction_code: "us_co", position: "agent", occupation: nil, company_name: "Dispatched Off Road", company_number: 20131414744},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "GIVING PLEDGE, LLC", company_number: 603033499},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "IRIS HOLDINGS, LLC", company_number: 602454362},
  {name: "BILL GATES", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "SOUTH CENTRAL ROTARY YOUTH EXCHANGE, INC.", company_number: 800168013},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "THE RIDGE HOMEOWNERS' ASSOCIATION", company_number: 601113324},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "TALPA LIVING WATER COWBOY CHURCH", company_number: 800330208},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SEABEAR COMPANY", company_number: 600544166},
  {name: "BILL GATES", jurisdiction_code: "gb", position: "director", occupation: "BUSINESS ANALYST", company_name: "LANGUAGE DIFFERENCE LIMITED", company_number: 4407549},
  {name: "BILL GATES", jurisdiction_code: "us_az", position: "other officer", occupation: nil, company_name: "PHOENIX ECONOMIC PARTNERS", company_number: 1687952},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "UTI INTEGRATED LOGISTICS, INC.", company_number: 2081001},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "director", occupation: nil, company_name: "COLDBROOK RECREATION COMMISSION", company_number: 1257032},
  {name: "BILL GATES", jurisdiction_code: "ca", position: "director", occupation: nil, company_name: "CANADIAN WELDING SOCIETY INCORPORATED -", company_number: 3334724},
  {name: "BILL GATES", jurisdiction_code: "us_or", position: "agent", occupation: nil, company_name: "OREGON RIBBON LIFT-OFF, INC.", company_number: 18054288},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "vp/interim recording", occupation: nil, company_name: "HALIFAX COUNTY CONDOMINIUM CORPORATION NO. 266", company_number: 3176533},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "GATOR'S PAWN SHOP INC", company_number: 108541000},
  {name: "BILL GATES", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "UTI INTEGRATED LOGISTIC, INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "BIOCARE, INC.", company_number: 42537154},
  {name: "BILL GATES", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "GATES PLUMBING INCORPORATED", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "WESTFIELD REALTY, INC.", company_number: 387066},
  {name: "BILL GATES", jurisdiction_code: "us_ms", position: "incorporator", occupation: nil, company_name: "GULF COAST PHOTO CENTER, INC.", company_number: 630764},
  {name: "BILL GATES", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "JAMES IRVINE INTERMEDIATE PARENT TEACHER ORGANIZATION", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "LIBERTY ANALYTICAL, LLC", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "ADVANCED MATERIALS DEFENSE TECHNOLOGIES, LLC", company_number: 0},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "principal", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES LLC", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "BILL GATES LLC", company_number: 4123639},
  {name: "BILL GATES SR", jurisdiction_code: "us_hi", position: "agent", occupation: nil, company_name: "EASTER HEAVENLY GATES FOUNDATION", company_number: 218108},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "GIVING PLEDGE, LLC", company_number: 603033499},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "IRIS HOLDINGS, LLC", company_number: 602454362},
  {name: "BILL GATES", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "SOUTH CENTRAL ROTARY YOUTH EXCHANGE, INC.", company_number: 800168013},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "THE RIDGE HOMEOWNERS' ASSOCIATION", company_number: 601113324},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "TALPA LIVING WATER COWBOY CHURCH", company_number: 800330208},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SEABEAR COMPANY", company_number: 600544166},
  {name: "BILL GATES", jurisdiction_code: "gb", position: "director", occupation: "BUSINESS ANALYST", company_name: "LANGUAGE DIFFERENCE LIMITED", company_number: 4407549},
  {name: "BILL GATES", jurisdiction_code: "us_az", position: "other officer", occupation: nil, company_name: "PHOENIX ECONOMIC PARTNERS", company_number: 1687952},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "UTI INTEGRATED LOGISTICS, INC.", company_number: 2081001},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "director", occupation: nil, company_name: "COLDBROOK RECREATION COMMISSION", company_number: 1257032},
  {name: "BILL GATES", jurisdiction_code: "ca", position: "director", occupation: nil, company_name: "CANADIAN WELDING SOCIETY INCORPORATED -", company_number: 3334724},
  {name: "BILL GATES", jurisdiction_code: "us_or", position: "agent", occupation: nil, company_name: "OREGON RIBBON LIFT-OFF, INC.", company_number: 18054288},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "vp/interim recording", occupation: nil, company_name: "HALIFAX COUNTY CONDOMINIUM CORPORATION NO. 266", company_number: 3176533},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "GATOR'S PAWN SHOP INC", company_number: 108541000},
  {name: "BILL GATES", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "UTI INTEGRATED LOGISTIC, INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "BIOCARE, INC.", company_number: 42537154},
  {name: "BILL GATES", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "GATES PLUMBING INCORPORATED", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "WESTFIELD REALTY, INC.", company_number: 387066},
  {name: "BILL GATES", jurisdiction_code: "us_ms", position: "incorporator", occupation: nil, company_name: "GULF COAST PHOTO CENTER, INC.", company_number: 630764},
  {name: "BILL GATES", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "JAMES IRVINE INTERMEDIATE PARENT TEACHER ORGANIZATION", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "LIBERTY ANALYTICAL, LLC", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "ADVANCED MATERIALS DEFENSE TECHNOLOGIES, LLC", company_number: 0},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "principal", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES LLC", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "BILL GATES LLC", company_number: 4123639},
  {name: "BILL GATES SR", jurisdiction_code: "us_hi", position: "agent", occupation: nil, company_name: "EASTER HEAVENLY GATES FOUNDATION", company_number: 218108},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ct", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177320},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ma", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177310},
  {name: "ADAM ENBAR", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 603513913},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "AME SOUPS, LLC", company_number: 3406788},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 4549544},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ct", position: "cofounder", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177320},
  {name: "ADAM ENBAR", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 0},
  {name: "ENBAR,ADAM", jurisdiction_code: "us_hi", position: "director", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 57928},
  {name: "ENBAR,ADAM", jurisdiction_code: "us_hi", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 57928},
  {name: "Boyd, Larry Page", jurisdiction_code: "us_ms", position: "agent", occupation: nil, company_name: "Pioneer Motors of Mississippi, LLC", company_number: 894547},
  {name: "DAVID LARRY PAGE JR", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "PAGE HOME IMPROVEMENT LLC", company_number: 0},
  {name: "LARRY A PAGE", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "ALLRIGHT WEST PALM BEACH, INC.", company_number: 179021},
  {name: "LARRY A PAGE", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "ALLRIGHT FLORIDA, INC.", company_number: 189439},
  {name: "LARRY A. PAGE", jurisdiction_code: "us_ma", position: "treasurer", occupation: nil, company_name: "AZURE PROP, INC.", company_number: 760072656},
  {name: "LARRY A. PAGE", jurisdiction_code: "us_ma", position: "treasurer", occupation: nil, company_name: "ALLRIGHT NEW YORK PARKING, INC.", company_number: 581773},
  {name: "LARRY D PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "LARRY D. PAGE, INC.", company_number: 145455300},
  {name: "LARRY D PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "BMM DEVELOPMENT INC", company_number: 802786440},
  {name: "LARRY D. PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "AP & M ASSOCIATES LLC", company_number: 800569899},
  {name: "LARRY D. PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "LIVANA COMMERCE INC", company_number: 802781014},
  {name: "LARRY E PAGE", jurisdiction_code: "us_ut", position: "agent", occupation: nil, company_name: "BAAL MEDICAL PRODUCTS, INC.", company_number: 1067633},
  {name: "LARRY E PAGE", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "PAGE HEATING AND COOLING, LLC", company_number: 0},
  {name: "LARRY E PAGE", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "PAGE HEATING AND COOLING, LLC", company_number: 0},
  {name: "LARRY E PAGE", jurisdiction_code: "us_nv", position: "manager", occupation: nil, company_name: "HAZMAT TERMINATORS, LLC", company_number: 0},
  {name: "LARRY F PAGE III", jurisdiction_code: "us_tn", position: "agent", occupation: nil, company_name: "TENNESSEE HARDWOOD PELLETS, LLC", company_number: 743280},
  {name: "LARRY G PAGE", jurisdiction_code: "us_wv", position: "vice-president", occupation: nil, company_name: "SHOWBIZ PIZZA TIME, INC.", company_number: 179358},
  {name: "LARRY G PAGE", jurisdiction_code: "us_tn", position: "agent", occupation: nil, company_name: "ELEC-TECH ELECTRICAL SERVICES, INC.", company_number: 235170},
  {name: "LARRY G. PAGE", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "A. J. A. S. INC.", company_number: 2010033100728},
  {name: "LARRY G. PAGE", jurisdiction_code: "us_ms", position: "treasurer", occupation: nil, company_name: "SHOWBIZ PIZZA TIME, INC.", company_number: 523745},
  {name: "LARRY J PAGE", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "QD EXPRESS INCORPORATED", company_number: 2424},
  {name: "LARRY JR. PAGE", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "LLHP&EE, LLC", company_number: 0},
  {name: "LARRY L PAGE SR", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "KITCHEN WORKS, INC.", company_number: 8604749},
  {name: "LARRY L PAGE SR", jurisdiction_code: "us_az", position: "president", occupation: nil, company_name: "KITCHEN WORKS, INC.", company_number: 8604749},
  {name: "LARRY L. PAGE", jurisdiction_code: "us_ar", position: "agent", occupation: nil, company_name: "LIBERTY MEMORIAL CEMETERY", company_number: 100078526},
  {name: "LARRY PAGE", jurisdiction_code: "us_ut", position: "agent", occupation: nil, company_name: "EC CONSTRUCTION MANAGEMENT, LLC", company_number: 8121195},
  {name: "LARRY PAGE", jurisdiction_code: "us_wa", position: "agent", occupation: nil, company_name: "COLVILLE FAMILY RADIO", company_number: 602125652},
  {name: "LARRY PAGE", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "ARKANSAS FAITH AND ETHICS COUNCIL", company_number: 100089044},
  {name: "LARRY PAGE", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "THE BIG CAT FOOTBALL BOOSTER CLUB, INC.", company_number: 801722784},
  {name: "LARRY PAGE", jurisdiction_code: "gb", position: "director", occupation: "RECORD PRODUCER", company_name: "PAGE ONE RECORDS LIMITED", company_number: 3595876},
  {name: "LARRY PAGE", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "L.P. Asset Recovery, Inc.", company_number: 567527},
  {name: "SERGEY BRIN", jurisdiction_code: "gb", position: "director", occupation: "PRESIDENT, ALPHABET INC", company_name: "GALVANI BIOELECTRONICS LIMITED", company_number: 9984862},
  {name: "SERGEY BRIN", jurisdiction_code: "us_nm", position: "director", occupation: nil, company_name: "GOOGLE INC.", company_number: 4667387},
  {name: "SERGEY BRIN", jurisdiction_code: "gb", position: "director", occupation: "COMPANY DIRECTOR", company_name: "GOOGLE UK LIMITED", company_number: 3977902},
  {name: "SERGEY BRIN", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "GOOGLE INC.", company_number: 0}
])
