Company.create!([
  {name: "\"A.O.A. BIG GOLDEN APPLE, INC.\"", company_number: 1998014, status: "Inactive   Dissolution", jurisdiction_code: "us_ny", incorporation_date: "1998-10-01 00:00:00", dissolution_date: "1998-01-05 00:00:00", address: "OLEG MOVSUNOV, 2780 WEST 5TH ST APT 19-A, BROOKLYN, NEW YORK, 11224", location_id: 1},
  {name: "1 APPLE GROCERY INC", company_number: 0, status: "Inactive", jurisdiction_code: "us_fl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "1 Apple, Inc.", company_number: 128, status: "Exists", jurisdiction_code: "us_al", incorporation_date: "2018-10-24 10:06:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "100TH RED APPLE SUPERMARKET INC.", company_number: 363029, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: "1999-12-29 00:00:00", address: "STEIN ROSEN & OHRENSTEIN, 1370 AVE OF AMERICAS, NEW YORK, NEW YORK, 10019", location_id: 1},
  {name: "101 APPLE CONSULTANTS, INC", company_number: 0, status: "Active", jurisdiction_code: "us_fl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "107TH ST. RED APPLE SUPERMARKET, INC.", company_number: 862776, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: "2002-06-26 00:00:00", address: "LOWENTHAL LANDAU FISCHER &, ZIEGLER, P.C., 250 PARK AVE., NEW YORK, NEW YORK, 10177", location_id: 1},
  {name: "124 APPLE BLOSSOM LANE INC", company_number: 100421041, status: nil, jurisdiction_code: "us_nj", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "12TH ST. RED APPLE SUPER DRUGS, INC.", company_number: 911719, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: "1993-03-24 00:00:00", address: "LOWENTHAL LANDAU FISCHER &, ZIEGLER, P.C., 250 PARK AVE., NEW YORK, NEW YORK, 10177", location_id: 1},
  {name: "1526 RED APPLE SUPERMARKET, INC.", company_number: 493114, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: "1992-03-25 00:00:00", address: "%STEIN ROSEN OHRENSTEIN, ATT: LEWIS HENKIND, 1370 AVE OF AMERICAS, NEW YORK, NEW YORK, 10019", location_id: 1},
  {name: "168 LUCKY RED APPLE NAIL INC.", company_number: 4369523, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "4369-10-01 00:00:00", dissolution_date: nil, address: "1426 NOSTRAND AVE., BROOKLYN, NEW YORK, 11226", location_id: 1},
  {name: "1724 RED APPLE INC.", company_number: 4527133, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "4527-10-01 00:00:00", dissolution_date: nil, address: "1724 HYLAN BLVD, STATEN ISLAND, NEW YORK, 10305", location_id: 1},
  {name: "1ST APPLE OIL & GAS INC", company_number: 0, status: "Ftb Suspended", jurisdiction_code: "us_ca", incorporation_date: "3611-10-01 00:00:00", dissolution_date: nil, address: "468 NORTH CAMDEN DR\nBEVERLY HILLS CA 90210", location_id: 1},
  {name: "2034 APPLE GROCERY & PRODUCE INC", company_number: 4952080, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "4952-10-01 00:00:00", dissolution_date: nil, address: "2034 EASTCHESTER RD, BRONX, NEW YORK, 10461", location_id: 1},
  {name: "226 APPLE, INC.", company_number: 1043469, status: nil, jurisdiction_code: "us_ma", incorporation_date: nil, dissolution_date: "2014-06-30 00:00:00", address: "16 PINE STREET, SUITE 2, LOWELL,, MA, 01851", location_id: 1},
  {name: "2319 APPLE, INC.", company_number: 0, status: "Active", jurisdiction_code: "us_ca", incorporation_date: "3592-10-01 00:00:00", dissolution_date: nil, address: "2323 APPLE AVE\nTORRANCE CA 90501", location_id: 1},
  {name: "24 HOUR APPLE LOCKSMITH INC.", company_number: 0, status: "Inactive", jurisdiction_code: "us_fl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "24TH RED APPLE SUPERMARKET INC.", company_number: 334724, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: "2000-12-27 00:00:00", address: "STEPHEN N. DRAKE, 3460 IRWIN AVE., BRONX, NEW YORK, 10463", location_id: 1},
  {name: "251 APPLE TREE COURT CONDOMINIUMS ASSOCIATION, INC.", company_number: 0, status: "Dissolved Nonprofit", jurisdiction_code: "us_mo", incorporation_date: nil, dissolution_date: "1999-11-09 00:00:00", address: "1400 E. ST. EUNICE\nFULTON, MO 65251", location_id: 1},
  {name: "27 APPLE INC.", company_number: 4541874, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "4541-10-01 00:00:00", dissolution_date: nil, address: "248-44 DEEPDALE AVENUE, LITTLE NECK, NEW YORK, 11362", location_id: 1},
  {name: "277 CLUB GREEN APPLE INC.", company_number: 358605, status: "Active", jurisdiction_code: "us_ny", incorporation_date: nil, dissolution_date: nil, address: "NONE", location_id: 1},
  {name: "290 APPLE INC.", company_number: 4724197, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "4724-10-01 00:00:00", dissolution_date: nil, address: "12 ELZEY AVENUE, ELMONT, NEW YORK, 11003", location_id: 1},
  {name: "312 APPLE TREE, INC.", company_number: 1642759, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: "1642-10-01 00:00:00", dissolution_date: "1999-12-29 00:00:00", address: "312 COURT STREET, BROOKLYN, NEW YORK, 11201", location_id: 1},
  {name: "319 BIG APPLE DRY CLEANERS, INC.", company_number: 1175069, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: "1175-10-01 00:00:00", dissolution_date: "1993-03-24 00:00:00", address: "319 FIRST AVENUE, NEW YORK, NEW YORK, 10003", location_id: 1},
  {name: "349 BIG APPLE DELI-GROCERY, INC.", company_number: 1622343, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: "1622-10-01 00:00:00", dissolution_date: "1997-09-24 00:00:00", address: "349 EAST 194TH STREET, BRONX, NEW YORK, 10458", location_id: 1},
  {name: "36 APPLE INC.", company_number: 2570589, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: "2570-10-01 00:00:00", dissolution_date: "2004-06-30 00:00:00", address: "345 W 36TH STREET 5/FL, NEW YORK, NEW YORK, 10018", location_id: 1},
  {name: "3RD APPLE DEVELOPMENT, INC.", company_number: 3758759, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "3758-10-01 00:00:00", dissolution_date: nil, address: "715 CENTRAL AVENUE, DUNKIRK, NEW YORK, 14048", location_id: 1},
  {name: "4819 & 4821 APPLE ROAD CONDOMINIUM OWNERS' ASSOCIATION, INC.", company_number: 0, status: "Incorporated/Qualified/Registered", jurisdiction_code: "us_wi", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "49 APPLE GROCERY INC.", company_number: 2816375, status: "Inactive   Dissolution", jurisdiction_code: "us_ny", incorporation_date: "2816-10-01 00:00:00", dissolution_date: "2016-05-20 00:00:00", address: "49 VICTORY BOULEVARD, STATEN ISLAND, NEW YORK, 10301", location_id: 1},
  {name: "721 APPLE FARMS INC.", company_number: 471113, status: "Inactive   Dissolution By Proclamation / Annulment Of Authority", jurisdiction_code: "us_ny", incorporation_date: "0047-11-13 00:00:00", dissolution_date: "1982-09-29 00:00:00", address: "KEVIN KO, 162-15 HIGHLAND AVE, JAMAICA, NEW YORK, 11432", location_id: 1},
  {name: "8 APPLE ASSOCIATION INC.", company_number: 0, status: "Inactive", jurisdiction_code: "us_fl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "51 TOORAK ROAD PTY LTD", company_number: 100103286, status: "Registered", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: "SOUTH YARRA, Victoria, 3141", location_id: 1},
  {name: "AED- FACEBOOK DETECTIVES, LLC", company_number: 0, status: "Revoked", jurisdiction_code: "us_nv", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "AEF - FACEBOOK DETECTIVES, LLC", company_number: 41097887, status: "Inactive   Action By Secretary Of State", jurisdiction_code: "us_la", incorporation_date: nil, dissolution_date: nil, address: "10000 CELTIC DR., CYPRESS BUILDING, SUITE C, BATON ROUGE, LA 70809", location_id: 1},
  {name: "AP602 IVS", company_number: 37522007, status: "Under Konkurs", jurisdiction_code: "dk", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "ATM FACEBOOK CARD, LLC", company_number: 0, status: "Active", jurisdiction_code: "us_fl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "CAC SALES L.L.C.", company_number: 9109634, status: "Active", jurisdiction_code: "us_ut", incorporation_date: "9109-10-01 02:00:00", dissolution_date: "2015-09-11 00:00:00", address: "2201 W ALEXANDER ST WEST VALLEY CITY, UT 84119", location_id: 1},
  {name: "CAROLINAS FACEBOOK, LLC", company_number: 638366, status: "Good Standing", jurisdiction_code: "us_sc", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "CORPORATION DES PRATICIENS EN MÉDECINE DOUCE DU QUÉBEC (C.P.M.D.Q.)", company_number: 1144361434, status: "Immatriculée", jurisdiction_code: "ca_qc", incorporation_date: nil, dissolution_date: nil, address: "1108 ch. Duhamel Pincourt (Québec) J7W4H1 Canada", location_id: 1},
  {name: "CURTIS-FACEBOOK LLC", company_number: 0, status: "Active, But Not In Good Standing As Of 2 16 2016", jurisdiction_code: "us_mi", incorporation_date: nil, dissolution_date: nil, address: "12296 HUBBARD LIVONIA MI 48150", location_id: 1},
  {name: "DENNY HILL/FACEBOOK LLC", company_number: 603186345, status: "Inactive", jurisdiction_code: "us_wa", incorporation_date: nil, dissolution_date: "2013-07-01 00:00:00", address: nil, location_id: 1},
  {name: "De Google Marketeer", company_number: 62499238, status: "Active", jurisdiction_code: "nl", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK ADDICTS LTD", company_number: 10346428, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2018-01-30 00:00:00", address: "123 Bath Row Birmingham City Centre, Birmingham, West Midlands, B15 1LS", location_id: 1},
  {name: "FACEBOOK ADS LTD", company_number: 10450546, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2018-04-03 00:00:00", address: "10450546: COMPANIES HOUSE DEFAULT ADDRESS, Cardiff, CF14 8LH", location_id: 1},
  {name: "FACEBOOK AND CO LTD", company_number: 7152749, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2011-09-20 00:00:00", address: "Victoria Suit Vintage House\n36-37 Albert Embankment, London, SE1 7TL", location_id: 1},
  {name: "FACEBOOK AUSTRALIA PTY LTD", company_number: 134012543, status: "Registered", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: "SYDNEY, New South Wales, 2000", location_id: 1},
  {name: "FACEBOOK BEIRUT, LLC", company_number: 3912170, status: nil, jurisdiction_code: "us_de", incorporation_date: "3912-10-01 00:00:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK BUSINESS INCUBATOR LIMITED", company_number: 8757776, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2015-06-16 00:00:00", address: "Kings Court\n33 King Street, Blackburn, BB2 2DH", location_id: 1},
  {name: "FACEBOOK CANADA LTD.", company_number: 1169720647, status: "Immatriculée", jurisdiction_code: "ca_qc", incorporation_date: nil, dissolution_date: nil, address: "2300 Yonge St Tower B Portion of 14th Floor Toronto ON M4P2W6 Canada", location_id: 1},
  {name: "FACEBOOK CANADA LTD.", company_number: 4496906, status: "Active", jurisdiction_code: "ca", incorporation_date: "4496-10-01 00:00:00", dissolution_date: nil, address: "661 University Avenue\nSuite 1201, 12th Floor, Toronto, ON, M5G 1M1", location_id: 1},
  {name: "FACEBOOK CO., LIMITED", company_number: 1645714, status: "Live", jurisdiction_code: "hk", incorporation_date: "1645-10-01 00:00:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK COFFEE SHOP", company_number: 80020000859964, status: "Registered", jurisdiction_code: "ug", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK COMMUNITY FUND", company_number: 0, status: "Active", jurisdiction_code: "us_ca", incorporation_date: "4153-10-01 00:00:00", dissolution_date: nil, address: "1601 WILLOW RD\nMENLO PARK CA 94025", location_id: 1},
  {name: "FACEBOOK ELECTRICAL PTY LTD", company_number: 151357569, status: "Deregistered", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: "2012-04-24 00:00:00", address: nil, location_id: 1},
  {name: "FACEBOOK ENSURE SOLUTIONS LTD", company_number: 8269158, status: "Active", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: nil, address: "Centenary House Upper First Floor\nPalliser Road, London, W14 9EQ", location_id: 1},
  {name: "FACEBOOK ENTERTAINMENT, LLC", company_number: 201709510498, status: "Active", jurisdiction_code: "us_ca", incorporation_date: nil, dissolution_date: nil, address: "1601 WILLOW ROAD\nMENLO PARK CA 94025", location_id: 1},
  {name: "FACEBOOK ENTERTAINMENT, LLC", company_number: 6347339, status: nil, jurisdiction_code: "us_de", incorporation_date: "6347-10-01 00:00:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK ESTATE LTD", company_number: 7816893, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2013-06-11 00:00:00", address: "595 Kings Road, London, SW6 2EL", location_id: 1},
  {name: "FACEBOOK EXECUTIVE GUEST HOUSE", company_number: 80020001120986, status: "Registered", jurisdiction_code: "ug", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "FACEBOOK FAN BUYER LTD", company_number: 7562472, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2012-05-08 00:00:00", address: "201 Luckwell Road, Bristol, Somerset, BS3 3HD", location_id: 1},
  {name: "FACEBOOK FAN EMPIRE, LLC", company_number: 2211358, status: "Active", jurisdiction_code: "us_oh", incorporation_date: "2211-10-01 00:00:00", dissolution_date: "2113-07-01 00:00:00", address: nil, location_id: 1},
  {name: "PAYPAL", company_number: 159998160, status: "Not Registered Organisations Of Type 'Nonc','Nret'", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL", company_number: 103074004, status: "Not Registered Organisations Of Type 'Nonc','Nret'", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL", company_number: 2009, status: "Ar Final Deregistration", jurisdiction_code: "za", incorporation_date: nil, dissolution_date: nil, address: "951 CHARL CILLIER STREET\nDASPOORT\n0182", location_id: 1},
  {name: "PAYPAL LTD", company_number: 0, status: "Dissolved", jurisdiction_code: "gb", incorporation_date: nil, dissolution_date: "2010-03-05 00:00:00", address: "58a Broughton Street, Edinburgh, Midlothian, EH1 3SA", location_id: 1},
  {name: "PAYPAL SECURE", company_number: 614237482, status: "Not Registered Organisations Of Type 'Nonc','Nret'", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Goodstanding", jurisdiction_code: "us_id", incorporation_date: nil, dissolution_date: nil, address: "2211 NORTH FIRST STREET C/O CORPORATE LEGAL DEPARTMENT SAN JOSE, CA 95131", location_id: 1},
  {name: "PAYPAL INC", company_number: 602762327, status: "Not Registered Organisations Of Type 'Nonc','Nret'", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 20041102371, status: "Good Standing", jurisdiction_code: "us_co", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Active Good Standing", jurisdiction_code: "us_mt", incorporation_date: nil, dissolution_date: nil, address: "2211 North First Street, c/o Corporate Legal Department, San Jose, California, 95131, United States", location_id: 1},
  {name: "PayPal, Inc.", company_number: 929, status: "Exists", jurisdiction_code: "us_al", incorporation_date: "2018-10-24 09:09:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 3689502, status: "Active And In Good Standing", jurisdiction_code: "us_ks", incorporation_date: "3689-10-01 00:00:00", dissolution_date: "2016-07-15 00:00:00", address: "LAURA A. CAREY - 2211 NORTH FIRST STREET, SAN JOSE, CA 95131", location_id: 1},
  {name: "PayPal, Inc.", company_number: 5235375, status: "Active", jurisdiction_code: "us_nm", incorporation_date: "5235-10-01 00:00:00", dissolution_date: nil, address: "1209 Orange Street, Wilmington, DE, 19801", location_id: 1},
  {name: "PayPal, Inc.", company_number: 6857, status: "Inactive", jurisdiction_code: "us_mn", incorporation_date: nil, dissolution_date: nil, address: "1010 Dale St N\nSt Paul, MN 55117–5603\nUSA", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Active", jurisdiction_code: "us_ca", incorporation_date: "2171-10-01 00:00:00", dissolution_date: nil, address: "2211 NORTH FIRST STREET, C/O CORPORATE LEGAL DEPARTMENT\nSAN JOSE CA 95131", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 770510487, status: nil, jurisdiction_code: "us_ma", incorporation_date: nil, dissolution_date: nil, address: "2211 NORTH FIRST STREET C/O CORPORATE LEGAL DEPARTMENT, SAN JOSE,, CA, 95131", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 3014267, status: nil, jurisdiction_code: "us_de", incorporation_date: "3014-10-01 00:00:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 12241, status: "Cancelled", jurisdiction_code: "pr", incorporation_date: "0012-10-01 01:12:00", dissolution_date: nil, address: "154 Rafael Cordero Ave.\nSuite 700\nSan Juan, PR 00901", location_id: 1},
  {name: "PAYPAL INC", company_number: 104778029, status: "Not Registered Organisations Of Type 'Nonc','Nret'", jurisdiction_code: "au", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Inactive", jurisdiction_code: "us_sd", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: nil, jurisdiction_code: "us_az", incorporation_date: nil, dissolution_date: nil, address: "3800 N CENTRAL AVE SUITE 460\nPHOENIX, AZ 85012", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 2779236, status: "Active", jurisdiction_code: "us_ny", incorporation_date: "2779-10-01 00:00:00", dissolution_date: nil, address: "111 EIGHTH AVENUE, NEW YORK, NEW YORK, 10011", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Revived", jurisdiction_code: "us_md", incorporation_date: nil, dissolution_date: nil, address: "2145 HAMILTON AVE\nSAN JOSE, CA 95125", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 2312150989, status: "In Existence", jurisdiction_code: "us_ok", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 290212, status: "Active", jurisdiction_code: "us_ia", incorporation_date: "0029-02-12 00:00:00", dissolution_date: nil, address: "2211 NORTH FIRST STREET, CO CORPORATE LEGAL DEPARTMENT, SAN JOSE, CA, 95131, USA", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 35220311, status: "Active   In Good Standing", jurisdiction_code: "us_la", incorporation_date: "3522-03-11 00:00:00", dissolution_date: nil, address: "3867 PLAZA TOWER DR.\nBATON ROUGE, LA 70816", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 100880027, status: nil, jurisdiction_code: "us_nj", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL FUNDS", company_number: 3052654, status: nil, jurisdiction_code: "us_de", incorporation_date: "3052-10-01 00:00:00", dissolution_date: nil, address: nil, location_id: 1},
  {name: "PAYPAL, INC.", company_number: 3075738, status: "Active", jurisdiction_code: "us_pa", incorporation_date: "3075-10-01 00:00:00", dissolution_date: nil, address: "C/O CT Corporation System Dauphin", location_id: 1},
  {name: "PayPal, Inc.", company_number: 0, status: "Active", jurisdiction_code: "us_va", incorporation_date: "1498-10-01 00:00:00", dissolution_date: nil, address: "2211 NORTH FIRST ST, C/O CORP LEGAL DEPT, SAN JOSE, CA, 95131", location_id: 1},
  {name: "PAYPAL, INC.", company_number: 0, status: "Revocation Of Certificate Of Authority", jurisdiction_code: "us_wi", incorporation_date: nil, dissolution_date: nil, address: nil, location_id: 1}
])
Director.create!([
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "ceo", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "THEFACEBOOK LLC", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 3842367},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FWD.US, INC.", company_number: 1132412},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "Facebook, Inc.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_mn", position: "chief executive officer", occupation: nil, company_name: "Facebook, Inc.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_nv", position: "treasurer", occupation: nil, company_name: "FWD.US, INC.", company_number: 0},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ct", position: "ceo/director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 883875},
  {name: "MARK ZUCKERBERG", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "Mark Zuckerberg", jurisdiction_code: "us_ga", position: "cfo", occupation: nil, company_name: "FWD.us, Inc", company_number: 17110153},
  {name: "Mark, Zuckerberg", jurisdiction_code: "us_nc", position: "president", occupation: nil, company_name: "Facebook, Inc.", company_number: 864380},
  {name: "ELON MUSK", jurisdiction_code: "us_ct", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 1075301},
  {name: "ELON MUSK", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 1077847},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "NEW WORLD INDUSTRIES, LLC", company_number: 201315610070},
  {name: "ELON MUSK", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 603589622},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "president/ceo", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "chairman of the board", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 4832094},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "director", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 4238655},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ri", position: "director", occupation: nil, company_name: "SolarCity Corporation", company_number: 920073},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "member", occupation: nil, company_name: "SOLAR INTEGRATED FUND III, LLC", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "chr", occupation: nil, company_name: "Space Exploration Technologies Corp.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "coe", occupation: nil, company_name: "Space Exploration Technologies Corp.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_nm", position: "chief executive officer", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 4832094},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 602455888},
  {name: "ELON MUSK", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "Tesla Motors, Inc.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ma", position: "ceo", occupation: nil, company_name: "TESLA, INC.", company_number: 1077847},
  {name: "ELON MUSK", jurisdiction_code: "gb", position: "director", occupation: "CEO", company_name: "SURREY SATELLITE TECHNOLOGY LIMITED", company_number: 1916260},
  {name: "ELON MUSK", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "TESLA, INC. OF LOUISIANA", company_number: 41303273},
  {name: "ELON MUSK", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "TESLA, INC.", company_number: 801471675},
  {name: "ELON MUSK", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_tx", position: "officer", occupation: nil, company_name: "TESLA, INC.", company_number: 801471675},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "TESLA, INC.", company_number: 602932644},
  {name: "ELON MUSK", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "SPACE EXPLORATION TECHNOLOGIES CORP.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "MUSK VENTURES, LLC", company_number: 200115210031},
  {name: "ELON MUSK", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "WORLD SPINE CARE", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "TESLA MOTORS", company_number: 3824277},
  {name: "ELON MUSK", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "TESLA MOTORS, INC.", company_number: 0},
  {name: "ELON MUSK", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SOLARCITY CORPORATION", company_number: 602924061},
  {name: "ELON MUSK", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "BFR INTERNATIONAL CORP.", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_nv", position: "president", occupation: nil, company_name: "AMAZON.COM FINANCIAL SERVICES, INC.", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "AMAZON.COM INSURANCE SERVICES, INC.", company_number: 602030690},
  {name: "JEFF BEZOS", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "NET MANAGERS, LLC", company_number: 0},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "AMAZON.COM.AS, INC.", company_number: 602032753},
  {name: "JEFF BEZOS", jurisdiction_code: "us_in", position: "president", occupation: nil, company_name: "LIVEBID.COM, INC.", company_number: 2000101700002},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "LIVEBID.COM, INC.", company_number: 601983997},
  {name: "JEFF BEZOS", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "TELEBOOK, INC.", company_number: 601872306},
  {name: "Jeff Bezos", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "NET MANAGERS, LLC", company_number: 0},
  {name: "EDWARD PETER VAN THIEL", jurisdiction_code: "gb", position: "director", occupation: "DIRECTOR", company_name: "COUNTRYWIDE DISTRIBUTION LIMITED", company_number: 4144228},
  {name: "EDWARD PETER VAN THIEL", jurisdiction_code: "gb", position: "director", occupation: "DIRECTOR", company_name: "EDWARD VAN THIEL LIMITED", company_number: 5825479},
  {name: "HANS PETER THIEL", jurisdiction_code: "pa", position: "director", occupation: nil, company_name: "COMERCIAL DA YU, S.A.", company_number: 10291},
  {name: "HANS PETER THIEL Y OTRO", jurisdiction_code: "pa", position: "secretario", occupation: nil, company_name: "COMERCIAL DA YU, S.A.", company_number: 10291},
  {name: "PETER A THIEL", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 999632},
  {name: "PETER M THIEL", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "CAP FERRAT TROIS, L.L.C.", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "NTS SEARCH MARKETING LLC", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "MARCO PRIME TIME, L.L.C.", company_number: 0},
  {name: "PETER M THIEL", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "NTS SEARCH MARKETING LLC", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "in", position: nil, occupation: nil, company_name: "FRAUSCHER SENSOR TECHNOLOGY INDIA PRIVATE LIMITED", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "in", position: nil, occupation: nil, company_name: "FRAUSCHER RAIL SIGNALLING SYSTEMS INDIA PRIVATE LIMITED", company_number: 0},
  {name: "PETER MICHAEL THIEL", jurisdiction_code: "gb", position: "director", occupation: "MANAGING DIRECTOR", company_name: "FRAUSCHER UK LIMITED", company_number: 7184154},
  {name: "PETER N THIEL", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "TRAIL RIDGE TRADING, INC.", company_number: 800230099},
  {name: "PETER N THIEL", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "TRAIL RIDGE TRADING, INC.", company_number: 800230099},
  {name: "PETER P THIEL", jurisdiction_code: "us_oh", position: "incorporator", occupation: nil, company_name: "MICROSYSTEM DESIGNS, INC.", company_number: 736806},
  {name: "PETER THIEL", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 41446269},
  {name: "PETER THIEL", jurisdiction_code: "us_ma", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 1017924},
  {name: "PETER THIEL", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "PETER THIEL ENGINEERING INC.", company_number: 2014110500141},
  {name: "PETER THIEL", jurisdiction_code: "us_ct", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 883875},
  {name: "PETER THIEL", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 801108427},
  {name: "PETER THIEL", jurisdiction_code: "us_ri", position: "director", occupation: nil, company_name: "Palantir Technologies Inc.", company_number: 822270},
  {name: "PETER THIEL", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 603164223},
  {name: "PETER THIEL", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "FACEBOOK, INC.", company_number: 0},
  {name: "PETER THIEL", jurisdiction_code: "us_va", position: "chairman", occupation: nil, company_name: "Palantir Technologies Inc.", company_number: 0},
  {name: "Peter Andreas THIEL", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "SECOND STAR LIMITED", company_number: 2378750},
  {name: "Peter Brooke Thiel", jurisdiction_code: "us_mn", position: "agent", occupation: nil, company_name: "Shiloh Studios LLC", company_number: 0},
  {name: "Peter Martin Thiel Søbjerg", jurisdiction_code: "dk", position: "interessenter", occupation: nil, company_name: "Thiel4", company_number: 39234408},
  {name: "Peter N Thiel", jurisdiction_code: "us_co", position: "agent", occupation: nil, company_name: "Trail Ridge Trading, Inc", company_number: 20051412887},
  {name: "Peter THIEL", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "SILVERARC ADVISORS LLC", company_number: 3061116},
  {name: "Peter Thiel", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "PALANTIR TECHNOLOGIES INC.", company_number: 0},
  {name: "JEFF A WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "CW MERCHANDIZE LIQUIDATORS, LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "vice president", occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "JMW REALTY CORP.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "ceo", occupation: nil, company_name: "MDW Insurance Services, Inc.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "secr", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_va", position: "trea", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "MDW SOUTH, LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "EMBRACE WELLNESS LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "VIP RISK ADVISORS LLC", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_nv", position: "director", occupation: nil, company_name: "A.I.R. INSURANCE MARKETING, INC.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "secretary", occupation: nil, company_name: "JMW REALTY CORP.", company_number: 0},
  {name: "JEFF B WEINER", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "CG THREE HOLDINGS, INC.", company_number: 0},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 1077535},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 14109071},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "A.I.R. INSURANCE MARKETING, INC.", company_number: 1172312},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ma", position: "secretary", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 1079691},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 3348018},
  {name: "JEFF B. WEINER", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "MDW INSURANCE GROUP, INC.", company_number: 3348018},
  {name: "JEFF E WEINER", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "MARCO UNIVERSAL, INC.", company_number: 0},
  {name: "JEFF HOWARD WEINER", jurisdiction_code: "gb", position: "director", occupation: "NATIONAL ACCOUNTS MANAGER", company_name: "CD INVITES U LTD", company_number: 4779770},
  {name: "JEFF HOWARD WEINER", jurisdiction_code: "gb", position: "director", occupation: "SALES MANAGER", company_name: "JEA MUSIC MANAGEMENT LIMITED", company_number: 3754689},
  {name: "JEFF W WEINER", jurisdiction_code: "us_va", position: "treasurer", occupation: nil, company_name: "Automotive Reconditioning Services, Inc.", company_number: 7314727},
  {name: "JEFF WEINER", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "INTUIT INC.", company_number: 601422317},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "PREMFIN CORPORATION", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "A-1 TILE INC.", company_number: 2302292},
  {name: "JEFF WEINER", jurisdiction_code: "us_tx", position: "director", occupation: nil, company_name: "AGENTS INSURANCE RESOURCES, INC.", company_number: 800988016},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "I & J HOLDINGS LLC", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_fl", position: "vice president", occupation: nil, company_name: "PREMFIN CORPORATION", company_number: 0},
  {name: "JEFF WEINER", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "JDJ&S ENTERPRISES, LLC", company_number: 0},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_nv", position: "managing member", occupation: nil, company_name: "JAMCAT INVESTMENTS LLC", company_number: 0},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_ma", position: "real property", occupation: nil, company_name: "WW 51 MELCHER LLC", company_number: 1110668},
  {name: "ADAM NEUMANN", jurisdiction_code: "us_ma", position: "real property", occupation: nil, company_name: "WW 745 ATLANTIC LLC", company_number: 1110665},
  {name: "Adam NEUMANN", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "NEUMANN CONTRACTORS LIMITED", company_number: 2083458},
  {name: "Adam NEUMANN", jurisdiction_code: "nz", position: "director", occupation: nil, company_name: "D A BUILDERS LIMITED", company_number: 3928982},
  {name: "Eric Adam Neumann", jurisdiction_code: "us_co", position: "agent", occupation: nil, company_name: "Dispatched Off Road", company_number: 20131414744},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "GIVING PLEDGE, LLC", company_number: 603033499},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "IRIS HOLDINGS, LLC", company_number: 602454362},
  {name: "BILL GATES", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "SOUTH CENTRAL ROTARY YOUTH EXCHANGE, INC.", company_number: 800168013},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "THE RIDGE HOMEOWNERS' ASSOCIATION", company_number: 601113324},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "TALPA LIVING WATER COWBOY CHURCH", company_number: 800330208},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SEABEAR COMPANY", company_number: 600544166},
  {name: "BILL GATES", jurisdiction_code: "gb", position: "director", occupation: "BUSINESS ANALYST", company_name: "LANGUAGE DIFFERENCE LIMITED", company_number: 4407549},
  {name: "BILL GATES", jurisdiction_code: "us_az", position: "other officer", occupation: nil, company_name: "PHOENIX ECONOMIC PARTNERS", company_number: 1687952},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "UTI INTEGRATED LOGISTICS, INC.", company_number: 2081001},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "director", occupation: nil, company_name: "COLDBROOK RECREATION COMMISSION", company_number: 1257032},
  {name: "BILL GATES", jurisdiction_code: "ca", position: "director", occupation: nil, company_name: "CANADIAN WELDING SOCIETY INCORPORATED -", company_number: 3334724},
  {name: "BILL GATES", jurisdiction_code: "us_or", position: "agent", occupation: nil, company_name: "OREGON RIBBON LIFT-OFF, INC.", company_number: 18054288},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "vp/interim recording", occupation: nil, company_name: "HALIFAX COUNTY CONDOMINIUM CORPORATION NO. 266", company_number: 3176533},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "GATOR'S PAWN SHOP INC", company_number: 108541000},
  {name: "BILL GATES", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "UTI INTEGRATED LOGISTIC, INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "BIOCARE, INC.", company_number: 42537154},
  {name: "BILL GATES", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "GATES PLUMBING INCORPORATED", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "WESTFIELD REALTY, INC.", company_number: 387066},
  {name: "BILL GATES", jurisdiction_code: "us_ms", position: "incorporator", occupation: nil, company_name: "GULF COAST PHOTO CENTER, INC.", company_number: 630764},
  {name: "BILL GATES", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "JAMES IRVINE INTERMEDIATE PARENT TEACHER ORGANIZATION", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "LIBERTY ANALYTICAL, LLC", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "ADVANCED MATERIALS DEFENSE TECHNOLOGIES, LLC", company_number: 0},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "principal", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES LLC", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "BILL GATES LLC", company_number: 4123639},
  {name: "BILL GATES SR", jurisdiction_code: "us_hi", position: "agent", occupation: nil, company_name: "EASTER HEAVENLY GATES FOUNDATION", company_number: 218108},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "GIVING PLEDGE, LLC", company_number: 603033499},
  {name: "BILL & MELINDA GATES FOUNDATIO", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "IRIS HOLDINGS, LLC", company_number: 602454362},
  {name: "BILL GATES", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "SOUTH CENTRAL ROTARY YOUTH EXCHANGE, INC.", company_number: 800168013},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "THE RIDGE HOMEOWNERS' ASSOCIATION", company_number: 601113324},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "TALPA LIVING WATER COWBOY CHURCH", company_number: 800330208},
  {name: "BILL GATES", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "SEABEAR COMPANY", company_number: 600544166},
  {name: "BILL GATES", jurisdiction_code: "gb", position: "director", occupation: "BUSINESS ANALYST", company_name: "LANGUAGE DIFFERENCE LIMITED", company_number: 4407549},
  {name: "BILL GATES", jurisdiction_code: "us_az", position: "other officer", occupation: nil, company_name: "PHOENIX ECONOMIC PARTNERS", company_number: 1687952},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "chairman", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "UTI INTEGRATED LOGISTICS, INC.", company_number: 2081001},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "director", occupation: nil, company_name: "COLDBROOK RECREATION COMMISSION", company_number: 1257032},
  {name: "BILL GATES", jurisdiction_code: "ca", position: "director", occupation: nil, company_name: "CANADIAN WELDING SOCIETY INCORPORATED -", company_number: 3334724},
  {name: "BILL GATES", jurisdiction_code: "us_or", position: "agent", occupation: nil, company_name: "OREGON RIBBON LIFT-OFF, INC.", company_number: 18054288},
  {name: "BILL GATES", jurisdiction_code: "ca_ns", position: "vp/interim recording", occupation: nil, company_name: "HALIFAX COUNTY CONDOMINIUM CORPORATION NO. 266", company_number: 3176533},
  {name: "BILL GATES", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "GATOR'S PAWN SHOP INC", company_number: 108541000},
  {name: "BILL GATES", jurisdiction_code: "us_ga", position: "ceo", occupation: nil, company_name: "UTI INTEGRATED LOGISTIC, INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_la", position: "director", occupation: nil, company_name: "BIOCARE, INC.", company_number: 42537154},
  {name: "BILL GATES", jurisdiction_code: "us_nv", position: "agent", occupation: nil, company_name: "GATES PLUMBING INCORPORATED", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "WESTFIELD REALTY, INC.", company_number: 387066},
  {name: "BILL GATES", jurisdiction_code: "us_ms", position: "incorporator", occupation: nil, company_name: "GULF COAST PHOTO CENTER, INC.", company_number: 630764},
  {name: "BILL GATES", jurisdiction_code: "us_ca", position: "agent", occupation: nil, company_name: "JAMES IRVINE INTERMEDIATE PARENT TEACHER ORGANIZATION", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "LIBERTY ANALYTICAL, LLC", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "UTI TRANSPORT SOLUTIONS-INTRANSIT INC.", company_number: 0},
  {name: "BILL GATES", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "ADVANCED MATERIALS DEFENSE TECHNOLOGIES, LLC", company_number: 0},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES JR", jurisdiction_code: "us_ar", position: "principal", occupation: nil, company_name: "THE CHURCH OF CHRISTIAN AND JEWISH FREEDOM", company_number: 800187104},
  {name: "BILL GATES LLC", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "BILL GATES LLC", company_number: 4123639},
  {name: "BILL GATES SR", jurisdiction_code: "us_hi", position: "agent", occupation: nil, company_name: "EASTER HEAVENLY GATES FOUNDATION", company_number: 218108},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "director", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "BILL, EMY GATES", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "SISTER INCORPORATED", company_number: 714934},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ct", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177320},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ma", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177310},
  {name: "ADAM ENBAR", jurisdiction_code: "us_wa", position: "governor", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 603513913},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ny", position: "dos process agent", occupation: nil, company_name: "AME SOUPS, LLC", company_number: 3406788},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ny", position: "chief executive officer", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 4549544},
  {name: "ADAM ENBAR", jurisdiction_code: "us_ct", position: "cofounder", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 1177320},
  {name: "ADAM ENBAR", jurisdiction_code: "us_fl", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 0},
  {name: "ENBAR,ADAM", jurisdiction_code: "us_hi", position: "director", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 57928},
  {name: "ENBAR,ADAM", jurisdiction_code: "us_hi", position: "president", occupation: nil, company_name: "FLATIRON SCHOOL, INC.", company_number: 57928},
  {name: "Boyd, Larry Page", jurisdiction_code: "us_ms", position: "agent", occupation: nil, company_name: "Pioneer Motors of Mississippi, LLC", company_number: 894547},
  {name: "DAVID LARRY PAGE JR", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "PAGE HOME IMPROVEMENT LLC", company_number: 0},
  {name: "LARRY A PAGE", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "ALLRIGHT WEST PALM BEACH, INC.", company_number: 179021},
  {name: "LARRY A PAGE", jurisdiction_code: "us_fl", position: "treasurer", occupation: nil, company_name: "ALLRIGHT FLORIDA, INC.", company_number: 189439},
  {name: "LARRY A. PAGE", jurisdiction_code: "us_ma", position: "treasurer", occupation: nil, company_name: "AZURE PROP, INC.", company_number: 760072656},
  {name: "LARRY A. PAGE", jurisdiction_code: "us_ma", position: "treasurer", occupation: nil, company_name: "ALLRIGHT NEW YORK PARKING, INC.", company_number: 581773},
  {name: "LARRY D PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "LARRY D. PAGE, INC.", company_number: 145455300},
  {name: "LARRY D PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "BMM DEVELOPMENT INC", company_number: 802786440},
  {name: "LARRY D. PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "AP & M ASSOCIATES LLC", company_number: 800569899},
  {name: "LARRY D. PAGE", jurisdiction_code: "us_tx", position: "agent", occupation: nil, company_name: "LIVANA COMMERCE INC", company_number: 802781014},
  {name: "LARRY E PAGE", jurisdiction_code: "us_ut", position: "agent", occupation: nil, company_name: "BAAL MEDICAL PRODUCTS, INC.", company_number: 1067633},
  {name: "LARRY E PAGE", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "PAGE HEATING AND COOLING, LLC", company_number: 0},
  {name: "LARRY E PAGE", jurisdiction_code: "us_fl", position: "agent", occupation: nil, company_name: "PAGE HEATING AND COOLING, LLC", company_number: 0},
  {name: "LARRY E PAGE", jurisdiction_code: "us_nv", position: "manager", occupation: nil, company_name: "HAZMAT TERMINATORS, LLC", company_number: 0},
  {name: "LARRY F PAGE III", jurisdiction_code: "us_tn", position: "agent", occupation: nil, company_name: "TENNESSEE HARDWOOD PELLETS, LLC", company_number: 743280},
  {name: "LARRY G PAGE", jurisdiction_code: "us_wv", position: "vice-president", occupation: nil, company_name: "SHOWBIZ PIZZA TIME, INC.", company_number: 179358},
  {name: "LARRY G PAGE", jurisdiction_code: "us_tn", position: "agent", occupation: nil, company_name: "ELEC-TECH ELECTRICAL SERVICES, INC.", company_number: 235170},
  {name: "LARRY G. PAGE", jurisdiction_code: "us_in", position: "agent", occupation: nil, company_name: "A. J. A. S. INC.", company_number: 2010033100728},
  {name: "LARRY G. PAGE", jurisdiction_code: "us_ms", position: "treasurer", occupation: nil, company_name: "SHOWBIZ PIZZA TIME, INC.", company_number: 523745},
  {name: "LARRY J PAGE", jurisdiction_code: "us_mi", position: "agent", occupation: nil, company_name: "QD EXPRESS INCORPORATED", company_number: 2424},
  {name: "LARRY JR. PAGE", jurisdiction_code: "us_fl", position: nil, occupation: nil, company_name: "LLHP&EE, LLC", company_number: 0},
  {name: "LARRY L PAGE SR", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "KITCHEN WORKS, INC.", company_number: 8604749},
  {name: "LARRY L PAGE SR", jurisdiction_code: "us_az", position: "president", occupation: nil, company_name: "KITCHEN WORKS, INC.", company_number: 8604749},
  {name: "LARRY L. PAGE", jurisdiction_code: "us_ar", position: "agent", occupation: nil, company_name: "LIBERTY MEMORIAL CEMETERY", company_number: 100078526},
  {name: "LARRY PAGE", jurisdiction_code: "us_ut", position: "agent", occupation: nil, company_name: "EC CONSTRUCTION MANAGEMENT, LLC", company_number: 8121195},
  {name: "LARRY PAGE", jurisdiction_code: "us_wa", position: "agent", occupation: nil, company_name: "COLVILLE FAMILY RADIO", company_number: 602125652},
  {name: "LARRY PAGE", jurisdiction_code: "us_ar", position: "director", occupation: nil, company_name: "ARKANSAS FAITH AND ETHICS COUNCIL", company_number: 100089044},
  {name: "LARRY PAGE", jurisdiction_code: "us_tx", position: "president", occupation: nil, company_name: "THE BIG CAT FOOTBALL BOOSTER CLUB, INC.", company_number: 801722784},
  {name: "LARRY PAGE", jurisdiction_code: "gb", position: "director", occupation: "RECORD PRODUCER", company_name: "PAGE ONE RECORDS LIMITED", company_number: 3595876},
  {name: "LARRY PAGE", jurisdiction_code: "us_pa", position: "president", occupation: nil, company_name: "L.P. Asset Recovery, Inc.", company_number: 567527},
  {name: "SERGEY BRIN", jurisdiction_code: "gb", position: "director", occupation: "PRESIDENT, ALPHABET INC", company_name: "GALVANI BIOELECTRONICS LIMITED", company_number: 9984862},
  {name: "SERGEY BRIN", jurisdiction_code: "us_nm", position: "director", occupation: nil, company_name: "GOOGLE INC.", company_number: 4667387},
  {name: "SERGEY BRIN", jurisdiction_code: "gb", position: "director", occupation: "COMPANY DIRECTOR", company_name: "GOOGLE UK LIMITED", company_number: 3977902},
  {name: "SERGEY BRIN", jurisdiction_code: "us_az", position: "director", occupation: nil, company_name: "GOOGLE INC.", company_number: 0}
])
Location.create!([
  {country: "United Kingdom", state: nil, city: "London", address: nil}
])
