Location.create!([
  {country: "United Kingdom", state: "London", city: "London", address: "30 Fenchurch Street", postcode: "EC3M 3BD"},
  {country: "United Kingdom", state: "Cambridgeshire", city: "Cambridge", address: "1 Francis Crick Avenue, Cambridge Biomedical Campus", postcode: "CB2 0AA"},
  {country: "United States", state: "Pennsylvania", city: "Philadelphia", address: "1500 Market St 35th Floor", postcode: "19102-0"},
  {country: "United States", state: "California", city: "Burbank", address: "500 S Buena Vista St", postcode: "91521"},
  {country: "United States", state: "New York", city: "New York", address: "111 Eighth Avenue", postcode: "10011"},
  {country: "United Kingdom", state: "London", city: "London", address: "1 St James's Square", postcode: "SW1Y 4PD"},
  {country: "United Kingdom", state: "Surrey", city: "Weybridge", address: "The Heights, Brooklands", postcode: "KT13 0XP"},
  {country: "United States", state: "California", city: "Menlo Park", address: "T1 Hacker Way (aka 1601 Willow Road)", postcode: nil}
])

Company.create!([
  {name: "Accenture (UK) Limited", company_number: 4757301, status: "active", jurisdiction_code: "gb", incorporation_date: "2003-05-08 00:00:00", location_id: 1, industry: "Consulting"},
  {name: "Astra Zeneca plc", company_number: 2723534, status: "active", jurisdiction_code: "gb", incorporation_date: "1992-06-17 00:00:00", location_id: 2, industry: "Pharmaceutical"},
  {name: "Comcast Corporation", company_number: 2714593, status: "active", jurisdiction_code: "us_pa", incorporation_date: "1996-09-16 00:00:00", location_id: 3, industry: "Telecommunications"},
  {name: "The Walt Disney Company", company_number: 0, status: "active", jurisdiction_code: "us_ca", incorporation_date: "1995-09-19 00:00:00", location_id: 4, industry: "Entertainment"},
  {name: "PepsiCo Inc", company_number: 1131190, status: "active", jurisdiction_code: "us_ny", incorporation_date: "1986-12-17 00:00:00", location_id: 5, industry: "Food"},
  {name: "BP P.L.C.", company_number: 102498, status: "active", jurisdiction_code: "gb", incorporation_date: "1909-04-17 00:00:00", location_id: 6, industry: "Oil & Gas"},
  {name: "Procter and Gamble (Health and Beauty Care) Limited", company_number: 436549, status: "active", jurisdiction_code: "gb", incorporation_date: "1947-06-06 00:00:00", location_id: 7, industry: "Pharmaceutical"},
  {name: "Facebook Inc.", company_number: nil, status: "Active", jurisdiction_code: "us-ca", incorporation_date: nil, location_id: 8, industry: "Technology"}
])

Director.create!([
  {name: "Aileen Louise Nathan", date_of_birth: nil},
  {name: "Alexander George Buckthorp", date_of_birth: nil},
  {name: "Anthony Joseph Appleton", date_of_birth: nil},
  {name: "Anthony Joseph Appleton", date_of_birth: nil},
  {name: "Christopher John Young", date_of_birth: nil},
  {name: "Daisy Victoria Gray", date_of_birth: nil},
  {name: "Gianluca Branda", date_of_birth: nil},
  {name: "Ian Morley", date_of_birth: nil},
  {name: "Rebecca Jane Goodall", date_of_birth: nil},
  {name: "Victoria Ann Ensla Tiffin", date_of_birth: nil},
  {name: "Vijay Indroo Sitlani", date_of_birth: nil},
  {name: "Alan Boeckmann", date_of_birth: nil},
  {name: "Alison Jane Carnwath", date_of_birth: nil},
  {name: "Ann Patricia Dowling", date_of_birth: nil},
  {name: "Antony Burgmans", date_of_birth: nil},
  {name: "Brendan Robert Nelson", date_of_birth: nil},
  {name: "Brian Gilvary", date_of_birth: nil},
  {name: "Carl-Henric Svanberg", date_of_birth: nil},
  {name: "David John Jackson", date_of_birth: nil},
  {name: "Denise Dillon", date_of_birth: nil},
  {name: "Frank Lee (“Skip”) Bowman", date_of_birth: nil},
  {name: "Freedom Phuthuma Nhleko", date_of_birth: nil},
  {name: "Hannah Ashdown", date_of_birth: nil},
  {name: "Helge Lund", date_of_birth: nil},
  {name: "Ian Edward Lamert Davis", date_of_birth: nil},
  {name: "Jens Bertelsen", date_of_birth: nil},
  {name: "Melody Boone Meyer", date_of_birth: nil},
  {name: "Nils Smedegaard Andersen", date_of_birth: nil},
  {name: "Pamela Daley", date_of_birth: nil},
  {name: "Paula Rosput Reynolds", date_of_birth: nil},
  {name: "Robert John Sawers", date_of_birth: nil},
  {name: "Robert Warren Dudley", date_of_birth: nil},
  {name: "Daniel Kenneth Burton", date_of_birth: nil},
  {name: "Emma Therese McGuigan", date_of_birth: nil},
  {name: "Oliver James Benzecry", date_of_birth: nil},
  {name: "Patrick Brian Francis Rowe", date_of_birth: nil},
  {name: "Patrick Brian Francis Rowe", date_of_birth: nil},
  {name: "Simon John Whitehouse", date_of_birth: nil},
  {name: "Zahra Bahrololoumi", date_of_birth: nil},
  {name: "Adrian Charles Noel Kemp", date_of_birth: nil},
  {name: "Deborah Disanzo Eldracher", date_of_birth: nil},
  {name: "Genevieve Bernadetter Berger", date_of_birth: nil},
  {name: "Graham Chipchase", date_of_birth: nil},
  {name: "Leif Valdemar Johansson", date_of_birth: nil},
  {name: "Marc Pierre Jean Dunoyer", date_of_birth: nil},
  {name: "Marcus Wallenberg", date_of_birth: nil},
  {name: "Pascal Claude Roland Soriot", date_of_birth: nil},
  {name: "Philip Arthur John Broadley", date_of_birth: nil},
  {name: "Rudolph Harold Peter Markham", date_of_birth: nil},
  {name: "Sabera Nazneen Rahman", date_of_birth: nil},
  {name: "Sherilyn Dawn McCoy", date_of_birth: nil},
  {name: "Shriti Vadera", date_of_birth: nil},
  {name: "Indra Nooyi", date_of_birth: nil},
  {name: "C Stephen Backstrom", date_of_birth: nil},
  {name: "John R Alchin", date_of_birth: nil},
  {name: "Stanley Wang", date_of_birth: nil},
  {name: "Stephen B Burke", date_of_birth: nil},
  {name: "Bob Iger", date_of_birth: nil},
  {name: "Indra Nooyi", date_of_birth: nil},
  {name: "Mark Zuckerberg", date_of_birth: nil}
])


CompanyDirector.create!([
  {company_id: 7, director_id: 2, position: "director"},
  {company_id: 7, director_id: 3, position: "director"},
  {company_id: 7, director_id: 4, position: "secretary"},
  {company_id: 7, director_id: 5, position: "director"},
  {company_id: 7, director_id: 6, position: "director"},
  {company_id: 7, director_id: 7, position: "director"},
  {company_id: 7, director_id: 8, position: "director"},
  {company_id: 7, director_id: 9, position: "director"},
  {company_id: 7, director_id: 10, position: "director"},
  {company_id: 7, director_id: 11, position: "director"},
  {company_id: 7, director_id: 12, position: "director"},
  {company_id: 6, director_id: 13, position: "director"},
  {company_id: 6, director_id: 14, position: "director"},
  {company_id: 6, director_id: 15, position: "director"},
  {company_id: 6, director_id: 16, position: "director"},
  {company_id: 6, director_id: 17, position: "director"},
  {company_id: 6, director_id: 18, position: "director"},
  {company_id: 6, director_id: 19, position: "director"},
  {company_id: 6, director_id: 20, position: "secretary"},
  {company_id: 6, director_id: 21, position: "secretary"},
  {company_id: 6, director_id: 22, position: "director"},
  {company_id: 6, director_id: 23, position: "director"},
  {company_id: 6, director_id: 24, position: "secretary"},
  {company_id: 6, director_id: 25, position: "director"},
  {company_id: 6, director_id: 26, position: "director"},
  {company_id: 6, director_id: 27, position: "secretary"},
  {company_id: 6, director_id: 28, position: "director"},
  {company_id: 6, director_id: 29, position: "director"},
  {company_id: 6, director_id: 30, position: "director"},
  {company_id: 6, director_id: 31, position: "director"},
  {company_id: 6, director_id: 32, position: "director"},
  {company_id: 6, director_id: 33, position: "director"},
  {company_id: 2, director_id: 34, position: "director"},
  {company_id: 1, director_id: 35, position: "director"},
  {company_id: 1, director_id: 36, position: "director"},
  {company_id: 1, director_id: 37, position: "secretary"},
  {company_id: 1, director_id: 38, position: "director"},
  {company_id: 1, director_id: 39, position: "director"},
  {company_id: 1, director_id: 40, position: "director"},
  {company_id: 6, director_id: 41, position: "secretary"},
  {company_id: 2, director_id: 42, position: "director"},
  {company_id: 2, director_id: 43, position: "director"},
  {company_id: 2, director_id: 44, position: "director"},
  {company_id: 2, director_id: 45, position: "director"},
  {company_id: 2, director_id: 46, position: "director"},
  {company_id: 2, director_id: 47, position: "director"},
  {company_id: 2, director_id: 48, position: "director"},
  {company_id: 2, director_id: 49, position: "director"},
  {company_id: 2, director_id: 50, position: "director"},
  {company_id: 2, director_id: 51, position: "director"},
  {company_id: 2, director_id: 52, position: "director"},
  {company_id: 2, director_id: 53, position: "director"},
  {company_id: 3, director_id: 54, position: "chief executive officer"},
  {company_id: 3, director_id: 55, position: "vice president"},
  {company_id: 3, director_id: 56, position: "secretary"},
  {company_id: 3, director_id: 57, position: "treasurer"},
  {company_id: 3, director_id: 58, position: "president"},
  {company_id: 4, director_id: 59, position: "Chief Executive Officer"},
  {company_id: 5, director_id: 60, position: "Chief Executive Officer"},
  {company_id: 8, director_id: 61, position: "Chief Executive Officer"}
])

